# Generated by Django 4.2.1 on 2023-06-05 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loan', serialize=False, to='task.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manufacturer', serialize=False, to='task.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='task.loanapplication'),
        ),
    ]
